services:
  laravel:
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: 123123
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_HOST: "%"
    volumes:
      - /laravel-mysql-data:/var/lib/mysql